# AI Novel Generator 配置文件
# 使用YAML格式，支持环境变量引用

# 最后使用的接口格式
last_interface_format: "OpenAI"
last_embedding_interface_format: "OpenAI"

# LLM模型配置
llm_configs:
  "DeepSeek V3":
    api_key: "${DEEPSEEK_API_KEY}"  # 从环境变量读取
    base_url: "https://api.deepseek.com/v1"
    model_name: "deepseek-chat"
    temperature: 0.7
    max_tokens: 8192
    timeout: 600
    interface_format: "OpenAI"
  
  "GPT 5":
    api_key: "${OPENAI_API_KEY}"  # 从环境变量读取
    base_url: "https://api.openai.com/v1"
    model_name: "gpt-5"
    temperature: 0.7
    max_tokens: 32768
    timeout: 600
    interface_format: "OpenAI"
  
  "Gemini 2.5 Pro":
    api_key: "${GEMINI_API_KEY}"  # 从环境变量读取
    base_url: "https://generativelanguage.googleapis.com/v1beta/openai"
    model_name: "gemini-2.5-pro"
    temperature: 0.7
    max_tokens: 32768
    timeout: 600
    interface_format: "OpenAI"
  
  "智谱GLM-4.5":
    api_key: "${ZHIPUAI_API_KEY}"  # 从环境变量读取
    base_url: "https://open.bigmodel.cn/api/paas/v4"
    model_name: "glm-4.5-air"
    temperature: 0.7
    max_tokens: 8192
    timeout: 600
    interface_format: "智谱"

# Embedding模型配置
embedding_configs:
  "OpenAI":
    api_key: "${OPENAI_EMBEDDING_API_KEY}"  # 从环境变量读取
    base_url: "https://api.openai.com/v1"
    model_name: "text-embedding-ada-002"
    retrieval_k: 4
    interface_format: "OpenAI"
  "SiliconFlow":
    api_key: "${SILICONFLOW_API_KEY}"  # 从环境变量读取
    base_url: "https://api.siliconflow.cn/v1"
    model_name: "BAAI/bge-m3"
    retrieval_k: 4
    interface_format: "SiliconFlow"
  "智谱":
    api_key: "${ZHIPUAI_API_KEY}"  # 从环境变量读取
    base_url: "https://open.bigmodel.cn/api/paas/v4"
    model_name: "embedding-2"
    retrieval_k: 4
    interface_format: "智谱"
  "Gitee AI":
    api_key: "${GITEE_AI_API_KEY}"  # 从环境变量读取
    base_url: "https://ai.gitee.com/v1"
    model_name: "bge-m3"
    retrieval_k: 4
    interface_format: "Gitee AI"

# 其他参数
other_params:
  topic: ""
  genre: ""
  num_chapters: 0
  word_number: 0
  filepath: "./novel_output"
  chapter_num: "120"
  user_guidance: ""
  characters_involved: ""
  key_items: ""
  scene_location: ""
  time_constraint: ""

# 选择的配置
choose_configs:
  prompt_draft_llm: "DeepSeek V3"
  chapter_outline_llm: "DeepSeek V3"
  architecture_llm: "Gemini 2.5 Pro"
  final_chapter_llm: "GPT 5"
  consistency_review_llm: "DeepSeek V3"

# 代理设置
proxy_setting:
  proxy_url: "127.0.0.1"
  proxy_port: ""
  enabled: false

# WebDAV配置
webdav_config:
  webdav_url: ""
  webdav_username: ""
  webdav_password: ""